apiVersion: v1
kind: Service
metadata:
  labels:
    app: ghost
  name: ghost
spec:
  type: NodePort
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ghost
